name: rich_text_example
description: AppFlowy Editor example for the rich_text component.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  appflowy_editor: ^6.2.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  universal_io: ^2.2.2
  rich_text:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
